export enum FilesUploaderEvents {
  FILES_UPLOADER_MAX_FILES_COUNT_REACHED = 'FILES_UPLOADER_MAX_FILES_COUNT_REACHED',
  FILES_UPLOADER_FILES_TO_UPLOAD_ADDED = 'FILES_UPLOADER_FILES_TO_UPLOAD_ADDED'
}
